version: '3.8'

services:
  config:
    build:
      context: .
      dockerfile: config.Dockerfile
    container_name: config
    ports:
      - "8888:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=prod

  discovery:
    build:
      context: .
      dockerfile: discovery.Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    depends_on:
      - config
    environment:
      - SPRING_PROFILES_ACTIVE=prod


  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    container_name: gateway
    depends_on:
      - config
    ports:
      - "8222:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  users:
    build:
      context: .
      dockerfile: users.Dockerfile
    container_name: users
    depends_on:
      - config
    environment:
      - SPRING_PROFILES_ACTIVE=prod